sudo: false
language: python

python:
  - "3.4"
  - "3.5"

env:
 - WSQL_TEST_DATABASE=wsql_test WSQL_TEST_USER=root CI_BUILD=1

before_install:
  - pip install -U pip setuptools
  - pip install -r requirements.dev.txt

install:
  - pip install .

before_script:
  - mysql -e 'create database wsql_test CHARACTER SET UTF8 COLLATE utf8_unicode_ci';

script:
 - ./run-tests

after_success:
 - coveralls

notifications:
  email: false
