language: python
python:
  - "3.4"

env:
 - WSQL_TEST_DATABASE=wsql_test WSQL_TEST_USER=root CI_BUILD=1

before_install:
  - pip install coveralls coverage

install:
  - pip install .

before_script:
  - mysql -e 'create database wsql_test CHARACTER SET UTF8 COLLATE utf8_unicode_ci';

script:
 - coverage run -m unittest discover --start-directory test
 - coverage report -m

after_success:
 - coveralls

notifications:
  email: false
